backend:
  name: github
  repo: nicolascampbell/MattSite
  branch: main # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  base_url: https://api.netlify.com 
  auth_endpoint: auth
media_folder: "public/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/public/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "pages"
    label: "Pages"
    format: json
    files:
    - label: "about"
      name: "About"
      file: "content/about.json"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}

